ventojs/vento

- .gitignore
- deno.json
- scripts/build_npm.ts
- test/print.test.ts
It is currently stuck in the "Print async filters" test of `print.test.ts`.
undici for node.js does not support `file://` url, will get a "not implemented yet" error (https://github.com/nodejs/undici/issues/2144)
Run the dnt build: `deno run -A scripts/build_npm.ts <version>`
> Provide npm package via `dnt`

- src/environment.ts
Somehow, when querying its cache for any already compiled templates, Vento uses the *path* when in actuality the templates are stored under the *file*. 
`undefined` shenanigans ensued.
> fix: use correct key for cache queries

- .vscode/settings.json
Just like the title says. This only disables it in VSCode though, so would ignoring all files in a `.prettierignore` be a better solution?
> chore: disable prettier formatting

- src/environment.ts
This adds a new lower-level hook called `tokenPreprocessors` to `Environment` that lets plugins transform a template's tokens into other tokens. It's like `tags`, except it isn't limited to a tag, and you output tokens.
Also adds support for URL query parameters. The sanitized path is passed to the loader, and the full path (with query strings) is passed to the token preprocessor, which unlocks a few capabilities.
One use for this is to add template fragments for the `htmx` library (https://htmx.org/essays/template-fragments/). Basically, you can mark up portions of the template that can be rendered individually. For example:
<details>
<summary>Template Fragments Example Plugin</summary>
```js
function fragmentPreprocessor(
env: Environment,
tokens: Token[],
path?: string
): Token[] | …
```
> Add token preprocessor hook and URL query parameters

- plugins/escape.ts
- plugins/unescape.ts
- test/escape.test.ts
- test/unescape.test.ts
Ran into this issue when using autoescape (but this also affects escaping values in general). This ensures any value that is passed into the filter is converted into a string. `html.escape` expects a string input, it doesn't convert the value automatically for you.
For example, this wouldn't work:
```js
const env = vento({
autoescape: true
});
const res = env.run("my-template.vto", { number: 10 });
```
```error
Error: Error in the template my-template.vto:11:5
{{ number }}
> str.replaceAll is not a function
```
> Fix: Convert any value to string when escaping

- scripts/build_npm.ts
Was working on a plugin for Vento that I also wanted to publish to npm. However, the types for it aren't exported anywhere in package.json, so I've added tokenizer and environment as entrypoints. Maybe could add loader too if that makes sense.
> Export tokenizer and environment

- deps.ts
- scripts/build_npm.ts
- src/environment.ts
- src/transformer.ts
The `with` statement comes with a lot of caveats, the main one (for me) is the huge performance penalty. JavaScript runtimes will de-optimize value accesses inside of `with` statements. I like the convenience of accessing state properties with just `{{ prop }}`, but since it has a huge perf penalty, I usually opt to disable `useWith`, which forces me to write templates with `it`.
Additionally, the generated code can't be used in strict mode.
Remove the `with` statement, and rewrite the generated JavaScript to insert the template state access.
Currently, it happens in a (~200 LoC) transform step that analyzes the AST of the generated code, and rewrites any unbound and non-global values to access from the template state. Accessing globals like `Deno`, `Promise`, `JSON` and other globals …
> Remove `with` usage in generated code, add code transform step

- plugins/layout.ts
- test/layout.test.ts
This is probably a weird use of layouts (I'm kinda using them like components). However, since most of my templates are already in a layout, this didn't work since it was just outputting to itself (the `__content` variable shadows the parent, which also is a layout setting the output var to `__content`).
Also added a test for this.
> Fix nested layouts

- docs/editor-integrations.md
Support for [tree-sitter-vento](https://github.com/ventojs/tree-sitter-vento) was just merged into [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter), so this adds some docs on setting up syntax highlighting for Neovim users.
> Document Neovim setup

- src/transformer.ts
- test/include.test.ts
Fixes #49. This will transform instances of:
```js
{
name
}
```
into
```js
{
name: it.name
}
```
> Fix object property shorthand

- .github/workflows/deno.yml
This can avoid errors like something occurred in https://github.com/ventojs/vento/actions/runs/8536415391/job/23384881018?pr=53 .
> skip deployment in PR

- plugins/echo.ts
Quick correction of a typo I noticed last week while writing my integration. Looks like the `echo` tag declaration was named `set` by accident.
> Typo Fix: correct echo tag function name

- .github/workflows/deno.yml
- .github/workflows/jsr.yml
- _scripts/build_npm.ts
- bench/bench.ts
- deno.json
- deps.ts
- src/tokenizer.ts
In prep for tackling #78, I have updated dependencies and also needed to handle a type assertion case because of how Typescript in Deno 2 handles error parameters in a `try ... catch` statement. This pull should bring everything up-to-date for running in Deno v2.
Hopefully nothing vastly breaking here but thought it best to open a seperate pull for these changes as they don't relate to #78.
> Updates for Deno 2

- deps.ts
- src/environment.ts
- src/transformer.ts
Here's an attempt to further improve #85. I'm not super happy with the implementation, since it feels like transform errors and template errors should be handled seperately. I didn't want to start refactoring everything so I tried to make these edits as reviewable as possible and keep the discussion going.
My reasoning for adding an annotated message logging the line of the compiled template function was to explain the errors that `meriyah` might throw and make it clear that the error is happening on a **compiled** function, not a user-authored one. To deal with these errors originating from the Eleventy integration, I also plan to add a message to my plugin reminding users to check for undeclared shortcodes and filters since those will cause errors when `meriyah` goes to parse/transform. …
> Improve transform error handling with compiled function annotations

- .vscode/settings.json
- src/environment.ts
- src/errors.ts
- src/transformer.ts
Ok! Here's the PR for the `errors.ts` file. I tried to be as conservative as possible with my edits and did a lot of research on the best way to implement 'default' properties in `class` declarations in TypeScript. I'm still pretty new to coding in TypeScript so I'm happy to make any corrections or edits if you would prefer things be handled differently.
Some quick notes to summarize things we discussed previously:
- I opted not to expose a `code` property on `TemplateError` instances since I think good error tracing can help identify the problem. 
- Likewise, I removed redundant logging of the `cause` message from `TemplateError` implementations, instead only including a short message with `cause.name` if it's defined. The `TransformError` message only adds context about the compiled JS …
> Implement `TransformError`/`TemplateError` subclasses

- src/errors.ts
Hi—sorry, quick patch here on the error subclass. 
I'd like to revert part of #89 by removing the lines that add `(via ErrorName)` to the error message. I got the idea to include that from Eleventy, but since Eleventy already includes that as a feature, you get error messages that duplicate the `(via ...)` text, like so:
```console
[11ty] Error in template src/vento.vto:1:61
[11ty] 
[11ty] <empty file>
[11ty] 
[11ty] (via TemplateError) (via TemplateError)
```
```console
[11ty] Error in template src/_includes/include.vto:1:1
[11ty] 
[11ty] {{ hello.hello }}
[11ty] 
[11ty] (via TypeError) (via TemplateError)
```
Is it better to leave the error handling (including `cause` chains, and the like) up to the implementation, like Eleventy, Lume, and others?
Sorry for the confusion!
> patch TemplateError to remove `cause.name` in `message`

- src/transformer.ts
- test/js.test.ts
Fixes #92, which incorrectly transformed the key instead of the property value. Also added an extra JS test to cover the other case.
> Fix property destruct codegen

- bare.ts
- mod.ts
Initially, I considered creating a separate `mini.ts`, but it would essentially be a full copy of `mod.ts` without plugin registration. I’d prefer to avoid duplicating the Vento creation logic.  
Then, I thought about adding `plugins: []` to the config and filling it with the default plugins by default, but it’s unclear how to use both all default plugins and a custom one at the same time.  
In the end, the `bare` flag seems like the simplest way to solve this problem. Changing the API might not be ideal, but all of these approaches modify the API in some way.
resolve #98
> Add bare flag to config

- plugins/echo.ts
- src/environment.ts
- src/tokenizer.ts
- test/echo.test.ts
The echo tag got some special handling within tokenization. Specifically it was transformed to an inline echo; for example, `{{echo}}foo{{/echo}}` was transformed to `{{echo "foo"}}`. This special handling isn't really needed, creates the perception of unreliable tokenization, and complicates making changes to the tokenization process.
It also created a subtle bug where it overwrote all of the whitespace trimming markers, because the tag was overwritten without explicitly handling their presence. This points to a deeper issue; custom plugins (including the trim plugin) can no longer rely on working together with the echo tag. Working with the `trim` plugin is a special case, since we cannot reliably detect what tags are echo tags within the tokenization process in general. However, …
> Genericize tokenzation of echo tags

- plugins/for.ts
- plugins/include.ts
- src/js.ts
- src/tokenizer.ts
- test/include.test.ts
The original `analyze` function takes a `visitor` argument, and this is a bit awkward to work with in isolation. To do performance optimizations, it is more ergonomic for this function to be lower level, taking only primitive arguments, reducing the entanglement with other parts of the codebase.
As such, I've reworked it to a `topLevel` function that reads a string of JavaScript until it encounters a character that "breaks" out of the top-level context; specifically this happens when it encounters a top-level `}`, `]`, or `|>`. The algorithm remains mostly the same, since conceptually the `analyze` function and `topLevel` function are doing very similar things.
The "include" tag here is a bit of an outlier. Its syntax is actually rather complex to get right, e.g. `include resolve({path: …
> Rework `analyze` function signature

- deps.ts
- plugins/escape.ts
- plugins/unescape.ts
- test/unescape.test.ts
This dependency is relatively large for what it does (>3kB), since it includes a comprehensive list of named HTML entities that Vento doesn't end up using. Instead, we can handle the logic in the "escape" and "unescape" plugins manually.
> Remove `jsr:@std/html` dependency

- docs/3.editor-integrations.md
Removed the instructions that add a new filetype. Newer versions of nvim (and vim) have the Vento filetype built-in.
> Update Neovim documentation

- bench/setup.ts
- plugins/escape.ts
This is for the v2 branch to avoid some conficts.
I noticed the benchmarks for Vento were with autoescape disabled, whereas most of the other template engines have it enabled by default. I found the performance of the escape to be pretty slow compared to PugJS (the only other fast templating engine) in particular, so this change fixes the performance.
Before:
```
benchmark         time/iter (avg)        iter/s      (min … max)           p75      p99     p995
----------------- ----------------------------- --------------------- --------------------------
Vento                    349.7 ns     2,860,000 (333.6 ns … 431.9 ns) 353.7 ns 414.4 ns 431.9 ns
VentoAutoescape            1.1 µs       895,800 (  1.1 µs …   1.3 µs)   1.1 µs   1.3 µs   1.3 µs
Pug                      677.4 ns …
```
> Faster escape filter (for v2)

- docs/index.md
Some feedback from the Eleventy Discord; it was mentioned that, from the homepage, it looks like Vento's main feature is the syntax change. This is not really accurate, as Vento has many things going for it that go beyond just being syntactically nicer to write. I've written what I think are the four main selling points; this includes the syntax change, but is last on the list.
> Show off selling points on homepage

- plugins/function.ts
- test/function.test.ts
I guess the `tokens.shift()` is a historical artifact, not sure - presumably this managed to go under the radar all this time just because the function declarations were being followed up by other tags or interpolation.
Fixes https://github.com/ventojs/vento/issues/147
> Fix static content after function being removed

- bench/setup.ts
- bench/templates/tmp.strict.vto
- core/environment.ts
- mod.ts
- plugins/set.ts
- test/echo.test.ts
- test/print.test.ts
- test/strict.test.ts
- test/utils.ts
This mode, which only makes sense when `autoDataVarname` is `true`, throws an error when an undeclared variable is used in a template. Currently Vento does not throw when doing something like `{{ foo }}` no matter whether not `foo` is declared (and renders nothing if it is undeclared/nullish). This can be problematic because typos can go unnoticed.
Resolves https://github.com/ventojs/vento/issues/101.
I've also added a separate benchmark for the strict mode. It uses a separate template, since the default Vento template references a `user` variable that doesn't exist and this throws in strict mode. Notably, the strict mode outperforms non-strict Vento in compilation and full benchmarks, because it skips iterating the template for variable name collection. It does lose by a lot in terms of …
> Strict mode

- CHANGELOG.md
- core/environment.ts
- test/strict.test.ts
Of course this is a bit minor, but I don't think it's accurate to say it's "much slower". The performance profile is different, but in some cases it actually ends up being _faster_ than Vento's default. Template compilation specifically is faster than usual because the generated JavaScript doesn't need to be iterated over to look for variable names. It's much slower in rendering, because it has to re-compile a new JS function every render, but rendering overall is already orders of magnitude faster than compilation, so this slowdown actually doesn't make it slower overall. For projects that have a lot of templates being rendered only once, the strict mode may prove to be faster.
I tried strict mode in lume.land's website, and (with some minor modifications to get around undefined …
> Strict mode is not slow

- core/environment.ts
- plugins/echo.ts
- plugins/function.ts
- plugins/import.ts
- plugins/include.ts
- plugins/layout.ts
- test/layout.test.ts
Adds a `env.getTempVariable()` method that creates a unique variable name for use in plugins. Also replaces some temp variable usage in existing core plugins.
The idea I had with `env.createScope()` didn't really work because it is incompatible with the way functions are built up as strings in Vento. I would like to, at some point, try to improve the plugin development experience, but for now this'll do just fine.
> Create unique temp variables

- plugins/set.ts
- test/set.test.ts
> Support for destructuring in set
